[server]
enableCORS = true
enableXsrfProtection = true
maxUploadSize = 10

[browser]
gatherUsageStats = false

[theme]
base = "dark"
primaryColor = "#C9A84C"

[react]
# إعدادات React
useWhitenoise = true
serveReactApp = false
